-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Tehtävä CASCADE; -- Muista IF EXISTS ja CASCADE parametrit!
DROP TABLE IF EXISTS Käyttäjä CASCADE;
DROP TABLE IF EXISTS Luokka CASCADE;