-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Tehtava CASCADE; -- Muista IF EXISTS ja CASCADE parametrit!
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Luokka CASCADE;